<template>
    <select class="block py-2.5  px-2 w-full text-sm text-gray-200 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer" name="Sehir">
        <option class="bg-sky-900 dark:bg-slate-900" value="" hidden>İl Seçiniz</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="İstanbul">İstanbul</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Ankara">Ankara</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="İzmir"  >İzmir</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Adana">Adana</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Adıyaman">Adıyaman</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Afyonkarahisar">Afyonkarahisar</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Ağrı">Ağrı</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Aksaray">Aksaray</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Amasya">Amasya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Antalya">Antalya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Ardahan">Ardahan</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Artvin">Artvin</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Aydın">Aydın</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Balıkesir">Balıkesir</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bartın">Bartın</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Batman">Batman</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bayburt">Bayburt</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bilecik">Bilecik</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bingöl">Bingöl</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bitlis">Bitlis</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bolu">Bolu</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Burdur">Burdur</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Bursa">Bursa</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Çanakkale">Çanakkale</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Çankırı">Çankırı</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Çorum">Çorum</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Denizli">Denizli</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Diyarbakır">Diyarbakır</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Düzce">Düzce</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Edirne">Edirne</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Elazığ">Elazığ</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Erzincan">Erzincan</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Erzurum">Erzurum</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Eskişehir">Eskişehir</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Gaziantep">Gaziantep</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Giresun">Giresun</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Gümüşhane">Gümüşhane</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Hakkâri">Hakkâri</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Hatay">Hatay</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Iğdır">Iğdır</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Isparta">Isparta</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kahramanmaraş">Kahramanmaraş</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Karabük">Karabük</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Karaman">Karaman</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kars">Kars</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kastamonu">Kastamonu</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kayseri">Kayseri</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kırıkkale">Kırıkkale</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kırklareli">Kırklareli</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kırşehir">Kırşehir</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kilis">Kilis</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kocaeli">Kocaeli</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Konya">Konya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Kütahya">Kütahya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Malatya">Malatya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Manisa">Manisa</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Mardin">Mardin</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Mersin">Mersin</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Muğla">Muğla</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Muş">Muş</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Nevşehir">Nevşehir</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Niğde">Niğde</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Ordu">Ordu</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Osmaniye">Osmaniye</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Rize">Rize</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Sakarya">Sakarya</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Samsun">Samsun</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Siirt">Siirt</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Sinop">Sinop</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Sivas">Sivas</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Şırnak">Şırnak</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Tekirdağ">Tekirdağ</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Tokat">Tokat</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Trabzon">Trabzon</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Tunceli">Tunceli</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Şanlıurfa">Şanlıurfa</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Uşak">Uşak</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Van">Van</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Yalova">Yalova</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Yozgat">Yozgat</option>
        <option class="bg-sky-900 dark:bg-slate-900" value="Zonguldak">Zonguldak</option>
    </select>
</template>